### PR TITLE
Adding ability to resend verification emails

### PR DESCRIPTION
**Pull request by amitnndn**
#1492 - Ability to Resend verification emails.

Added the ability to resend verification emails when on the screen where the user enters the verification code that they receive via email. 

This is still a WIP and I just wanted to get an early review of the code and placement of the 'Resend Verification Email' button. 

I have some questions/thoughts off the top of my head:
* Should the Resend Verification Email button disabled after the user clicks it for a specific amount of time? Just to avoid multiple emails being dispatched or overloading the API with multiple requests.
* Do we need any signifying text next to the button maybe explaining what it does? (I know this is a bad design, but I just wanted to get all my thoughts out)
* Maybe this is another issue or an improvement: There is no way that I can change my email through the verify email page. It would be nice to be able to change the email from the verification screen as well. 

### Preview
screen shot 2018-06-06 at 9 04 46 pm

P.S: This is one of the first React and Redux apps that I am working on, still trying to grasp the concepts of reducers, actions, selectors etc., forgive me if there are any silly mistakes! :-)

### CODE REVIEW

**Comment by amitnndn** [comment]
Thank you @seanyesmunt! I have changed updated the code as per your comments. Do you have any idea why the Travis CI builds might be failing? It shows a connectivity error, I am not sure if something I added is breaking it.

**Comment by seanyesmunt** [comment]
@amitnndn Looks like it's running now. Sometimes Travis just acts a little wonky 🙂

**Comment by seanyesmunt** [comment]
@amitnndn build passed 🙂 

I'll give this a test tomorrow morning but looks good.

**Comment by amitnndn** [comment]
@seanyesmunt Thank you! Let me know if you have any questions!

**Comment by tzarebczan** [comment]
@amitnndn, thanks for your first contribution! Please review our [contributing guide](https://lbry.io/faq/contributing) if you have not done so already. Also, [click here](https://lbry.io/faq/tips) if you are interested in an LBC tip for your work :)

We'll also be adding you to our developer mailing list so we can keep in touch (you can unsubscribe anytime!). 

To answer your question about changing the email, the short-term fix for that would be: https://github.com/lbryio/lbry-app/issues/997 (longer term - https://github.com/lbryio/lbry-app/issues/926)

**Comment by seanyesmunt** [comment]
Working great! Thanks for the contribution! 🙂

**Comment by amitnndn** [comment]
@tzarebczan @seanyesmunt Thank you very much! Looking forward to taking up more issues in my spare time! 👍

**Pull request merged**
