### PR TITLE
chore: migrate to AppImage and publish with electron-builder on Travis

### LINKED ISSUE #332: Use AppImage for Linux builds
[AppImage](http://appimage.org/) allows you to make a single executable that can run on any Linux distribution with no setup or dependencies required. According to @filipnyquist electron-builder already has support for it, so the daemon just needs some changes.

### LINKED ISSUE #966: Research publishing options and mystery ci upload
need to figure this out

### PR DESCRIPTION
**Pull request by IGassmann**
This closes #332 and closes #966.

### CODE REVIEW

**Comment by kauffj** [comment]
@JoshStrobl apologies if this is a redundant question (I have this feeling I've asked this), but for your purposes does this switch to AppImage: a) help, b) hurt, or c) doesn't matter?

**Comment by JoshStrobl** [comment]
@kauffj It doesn't affect packaging in my case. ("Doesn't matter.")

**Comment by tzarebczan** [comment]
@IGassmann per our convo, let's make sure the daemon is signed: https://github.com/lbryio/lbry/issues/811

**Comment by probonopd** [comment]
Now that this has been merged, where did the AppImage go?

**Comment by kauffj** [comment]
@seanyesmunt do you know what happened to AppImage builds or what it would take to re-enable these?

**Comment by tzarebczan** [comment]
We only temporarily tested with these and decided not to go with them at the time because it required setting the executable properties manually before installing. 

With syncing enabled now, I think it will be a good time to check out appimage and snaps.

**Comment by probonopd** [comment]
If you would like to test, here is an example AppImage I've made to be able tor run LBRY until an official AppImage becomes available:

https://github.com/probonopd/LBRY.AppImage/releases/tag/continuous

Before you can run an AppImage, you need to make it executable. This is a Linux security feature. There are three main ways to make an AppImage executable:

**1. With the GUI**



**2. On the command line**

```
chmod a+x Some.AppImage
```

**3. Automatically with the optional appimaged daemon**

If you would like to have all AppImages be executable automatically, you can install the optional `appimaged` daemon. It will automatically add downloaded AppImages to the menu and make them executable for you. It can be downloaded from https://github.com/AppImage/AppImageKit/releases or installed from your distribution.

If you haven't seen it, also check out this:

[](https://youtu.be/el6KTRV4Ej4?t=909)

**Pull request merged**
