### PR TITLE
FIX #1029 Update view.jsx

### LINKED ISSUE #1029: Add Rewards FAQ to LBRY app
## The Issue
Add link to Rewards FAQ (https://lbry.io/faq/rewards) in areas that mention rewards.

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by ykris45**
add rewards FAQ

### CODE REVIEW

**Comment by ykris45** [comment]
probably it should help #1029 .

**Comment by tzarebczan** [comment]
@ykris45 unless you have a development environment setup where you can test this, you should not be making code changes directly on Github.

**Comment by ykris45** [comment]
i didnt have it sir.

**Comment by tzarebczan** [comment]
I know you want to help, but without a proper testing environment in place where you can view and share your changes, we can't accept this.

**Pull request closed without merging**
