### PR TITLE
Update "Community Top Bids" info

### PR DESCRIPTION
**Pull request by kkorte**
#1668

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@kkorte Thanks for the PR! I think it might be better to say: 
`... Bid on the names "one," "two," "three," "four", "five" through "ten" ...`

**Comment by seanyesmunt** [comment]
Didn't mean to close this. Thanks for the PR! Let's keep the tooltip style the same for now. That issue is just for the community info text.

**Comment by seanyesmunt** [comment]
Hey @kkorte we ended up using the text from this PR instead. https://github.com/lbryio/lbry-app/pull/1680

**Comment by tzarebczan** [comment]
@kkorte if you'd like a tip for your contribution, please see https://lbry.io/faq/tips

**Pull request closed without merging**
