### PR TITLE
Add scam alert message when opening development tools.

### PR DESCRIPTION
**Pull request by dan1d**
Hi, I've took the liberty to work on issue #1430 as the issue is 20 days old and OP didn't answered if he was going to work on this.
It closes issue: #1430, adds a warning message when development tools is opened on production, it can be disabled on development but is active by default.
Let me know if I should change the log message, or if while on development it should be disabled.
screenshot from 2018-05-22 23-23-47

### CODE REVIEW

**Comment by kauffj** [comment]
Love the join us plug @dan1d :)

**Comment by seanyesmunt** [comment]
I don't think this should be logged in dev mode

**Comment by tzarebczan** [comment]
@dan1d tagging you to make sure you saw the above comment.

**Comment by dan1d** [comment]
Disabled on development by default!

**Pull request merged**
