### PR TITLE
[WIP] Support claim UI implementation

### PR DESCRIPTION
**Pull request by akinwale**
Added the Support Claim link and inline form to the view media page.

I'm still not exactly sure where total claim support should be displayed. Should it be enclosed within brackets suffixed to the button label or in the inline form?

### CODE REVIEW

**Comment by 6ea86b96** [comment]
I think it might be good to create a `actions/claims.js`. There should be one already, this is my fault. There's also a bunch of code in `actions/content.js` which really should not be there too.

**Comment by akinwale** [comment]
@6ea86b96 I guess this means I should also move the corresponding selectors and reducers from `selectors/file_actions.js` and `reducers/file_actions.js` to `selectors/claims.js` and `reducers/claims.js` respectively?

**Comment by 6ea86b96** [comment]
IMO yes, the supports stuff fits into claims better than file actions.

**Comment by kauffj** [comment]
This is in `tip_and_supports` branch and will come in via #391.

**Pull request closed without merging**
