### PR TITLE
Autoplay

### PR DESCRIPTION
**Pull request by daovist**
This PR implements an autoplay featured for issue #584 

Autoplay is a user setting which can be checked on/off on the settings and file pages. When on, it will play videos that have downloaded at least one blob. Otherwise, it will begin the download.

This adds a new icon and some CSS.

### CODE REVIEW

**Comment by seanyesmunt** [comment]
What about a snackbar message? That way we would display the info without affecting a playing video.

**Comment by seanyesmunt** [comment]
I'm really not a fan of having it on this page at all, because it won't do anything. If a video has already started, and they un-check it, the video will continue to play. And if a video isn't playing and they check it, it won't start playing. 

For the majority of people of who keep this setting on, it will just be an extra input on the page that they never interact with (unless by accident, and they wonder why the videos aren't playing anymore)

**Comment by kauffj** [comment]
@seanyesmunt if you want to remove it you are welcome to.

I will say that I think a snackbar is wrong. Snackbars are to give feedback related to actions the user took.

**Comment by seanyesmunt** [comment]
Still trying to see why it isn't playing for me. I think we can keep it. I think a better spot for it would be on the right side, below the tip/subscribe buttons.

**Comment by seanyesmunt** [comment]
@daovist Ah I realized why. You have a check to not autoplay if users have `obscureNSFW` as false. I think it's ok to play content if they have that setting checked, as long as the content is not marked NSFW. And in that case, there should be some help text under the checkbox saying "we won't autoplay this because you have NSFW content hidden" (not that but similar). It is really confusing in it's current state that it isn't playing because I have some other setting checked.

Another thing I would add is having some check inside `componentWillReceiveProps` to only call `handleAutoplay` if it's necessary, so it's not being called a bunch of times when data that isn't relevant to this piece of code is changing.

**Pull request merged**
