### PR TITLE
[FIX #1002] improve Quit app by click CTRL+Q [TESTED Locally]

### LINKED ISSUE #1002: Add menu / keyboard shortcut to Quit LBRY app
## The Issue
During the last refactor, looks like we lost the ability (at least on Windows/Linux) to completely quit the LBRY app from a menu/keyboard shortcut.  To quit the app right now, users need to right click on the tray icon > Quit.  

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by ykris45**

### CODE REVIEW

**Comment by ykris45** [comment]
@IGassmann confusing with codacy bot

**Comment by IGassmann** [comment]
@ykris45 You can find the explanation for each of the Codacy comments by clicking on the URLs and then clicking on the issues.

**Comment by ykris45** [comment]
@igassman oke i will learn to fix that

**Comment by ykris45** [comment]
@IGassmann why changelog marked X

**Comment by tzarebczan** [comment]
Chris, you'll need to close this PR and resubmit with just the changes for this ticket. The recent commits brought in other changes.

Make sure your local repo is up to date (git pull) before making changes. You may need to run git stash to overwrite your local changes before doing so. You should do some research about the proper way to push these changes from a local machine vs on the github website.

**Comment by ykris45** [comment]
@tzarebczan okay. will resubmit this again...my branch up to date sir

**Comment by kauffj** [comment]
@ykris45 time to level up your skills by learning git from the command line and what `git rebase` does ;)

**Comment by ykris45** [comment]
@kauffj thats is true. i must levelling up my skills ..  done #1150

**Pull request closed without merging**
