### PR TITLE
Update bid input field in view.jsx to not go past 0

### PR DESCRIPTION
**Pull request by aayanl**
#441

### CODE REVIEW

**Comment by aayanl** [comment]
oh looks like #439 already fixes this, closing

**Comment by btzr-io** [comment]
@aayanl  They probably never gonna merge #439 so go a head  :+1:  ^^

**Comment by btzr-io** [comment]
Also make sure to check all the inputs :upside_down_face:

**Comment by btzr-io** [comment]
also -> https://github.com/lbryio/lbry-app/pull/439/commits/1a7c036938e3e2905ac23f27c76d9a99f053a8c8

**Comment by btzr-io** [comment]
https://github.com/lbryio/lbry-app/pull/471

**Pull request merged**
