### PR TITLE
Check for valid address when sending credits on Wallet page

### LINKED ISSUE #445: Check Address is valid before sending
## The Issue
issue comes about when trying to send funds to a non legit account like "aaaaaaaa"
### Steps to reproduce
1.enter address aaaaaaaaaa
2.enter amount
3.send

### Expected behaviour
i would expect this to do an api call to see if this address is existence and has funds linked to it or if it does not have a public or private key don't send the funds, and have error pop up if it doesnt work 
### Actual behaviour
it claims it sent the funds to the non existence account

## System Configuration

 

- LBRY Daemon version: 0.14.2
- LBRY App version: 0.14.3
- LBRY Installation ID: 9JKT6nrdGYoFKshVLmjnbfUdqNvHRkzWmsLXk5xNdbXzGEwpraZ6MVg1KoD5jrBrf2
- Operating system: Windows 10

### PR DESCRIPTION
**Pull request by alexliebowitz**
Fixes #445. Ready to go, but https://github.com/lbryio/lbry/pull/867 needs to be merged first

### CODE REVIEW

**Comment by kauffj** [comment]
`is_address` will not be an API call. See discussion elsewhere.

More importantly, this is not solved as suggested by #445. See my comment [here](https://github.com/lbryio/lbry-app/issues/445#issuecomment-320525524).

Please solve this by simply adding a regexp parameter to `FormField` or a descendant of `FormField`. Then an invalid address can be detected and shown to the user entirely in widget-land -- no need for a modal.

I'm closing this PR as I think very little of it will apply to the appropriate solution.

(Btw, if you think the proposed approach is incorrect, I am, as always, open to discussion. I suspect in this base it simply wasn't seen.)

**Comment by alexliebowitz** [comment]
Ugh, yes, you're right, I missed it. I skimmed the whole thread but somehow took away that your idea was about implementation details (not UX). Should have gone over it again before I started work.

Is it really just a regex check to confirm a valid address, though? The JS libraries seem to do some base58 voodoo to check: https://github.com/cryptocoinjs/coinstring/blob/master/lib/coinstring.js#L53-L61 -> https://github.com/cryptocoinjs/coinstring/blob/master/lib/coinstring.js#L24-L39

In which case we could use the validator function from one of libraries (or write our own small validator function) and add a validator function param to form fields instead of a regex param.

**Comment by kauffj** [comment]
@alexliebowitz I think it is just `/^b[HJK][1-9A-Za-z][^OIl]{33}/` or something close to that...

**Comment by alexliebowitz** [comment]
@kauffj: @kaykurokawa says "regex can tell you if its base 58 encoded, but it won't validate it because there 's a checksum and a header byte". Checksum seems important, since it will notice typos where 1 character is off but it's still base58.

**Pull request closed without merging**
