### PR TITLE
Support for video duration within the UI

### PR DESCRIPTION
**Pull request by KamilPiekutowski**
This is should work with this schema:
[https://github.com/lbryio/lbryschema/pull/28](url)

and this lbry:
[https://github.com/lbryio/lbry/pull/945](url)

It only shows lengths with newly published videos.

### CODE REVIEW

**Comment by kauffj** [comment]
@KamilPiekutowski thanks for this contribution! It did seem to include some additional files you had related to logging.

However, this will be blocked either way until the code downstream in lbry is released at least in a daemon RC.

**Comment by kauffj** [comment]
Impressive that you managed to add this all the way up the stack!

**Comment by KamilPiekutowski** [comment]
I assume you haven't gotten time to see if this works. If you need to test it and have problems with it let me know.  As I mentioned in first comment, the changes done to lbryschema and lbry are necessary for it to work.

**Comment by kauffj** [comment]
I removed the log files and put this code in this branch: https://github.com/lbryio/lbry-app/tree/content-duration

This is blocked downstream and will be for several weeks minimum. I'm going to close this in the interim.

Please let me know if you haven't heard from our team on the other issues.

**Comment by KamilPiekutowski** [comment]
That sounds good. I have not heard anything from the other pull requests except for this PR:
[https://github.com/lbryio/lbry/pull/945](url)

I am not sure what will be decided about it.
If I can get more detailed feedback on it I can start working on fixes.

**Pull request closed without merging**
