### PR TITLE
some modification for main menu

### PR DESCRIPTION
**Pull request by ykris45**
Based ideas on https://github.com/lbryio/lbry-app/issues/1470 . 
image
i only add select all option and some keyboard shortcut to make this app looks more professional .
image

### CODE REVIEW

**Comment by tzarebczan** [comment]
@ykris45 there was some work on context menu here: https://github.com/lbryio/lbry-app/pull/1486 

Please see if your changes overlap ...maybe better to wait for that PR to get approved first.

**Comment by ykris45** [comment]
@seanyesmunt please review my PR

**Comment by tzarebczan** [comment]
@ykris45 did you see my comment in https://github.com/lbryio/lbry-app/pull/1513#issuecomment-391817570 ? There are conflicts with that code. Can you rebase your changes into master and test them locally, then submit again?

**Comment by ykris45** [comment]
closed this for now based @tzarebczan last comments

**Pull request closed without merging**
