### PR TITLE
Add Help button on top row of app

### LINKED ISSUE #809: Add Help button on top row of app
## The Issue
When a first run user encounters an issue, they can't easily find the "help/support" area. Right now its hidden under Settings. Would be nice to have a dedicated button at the right most area (after settings) which navigates there. 

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by ohwaitingtx**
Added a "Help" button/link to the right edge of the header.

Closes #809.

### CODE REVIEW

**Comment by tzarebczan** [comment]
Woohoo, thanks for the contribution! Can you attach a screenshot of what it looks like?

Check out https://lbry.io/faq/tips
:)

**Comment by ohwaitingtx** [comment]
Sure thing - I probably should've included it in the initial PR request: Screenshot showing "Help" button

**Comment by seanyesmunt** [comment]
The header is definitely getting a little crowded, but this will be nice to have until we decide how we what icons should go/stay.

Thanks for the contribution!

**Comment by liamcardenas** [comment]
@ohwaitingtx thanks for this! Have you seen our [contributing doc](https://github.com/lbryio/lbry-app/blob/master/CONTRIBUTING.md)?

**Comment by tzarebczan** [comment]
@liamcardenas we took care of it already, sent a tip :)

**Comment by liamcardenas** [comment]
@tzarebczan that's good, im glad he was compensated, but this didn't have a help wanted tag so I'm wondering why he chose it. Maybe the document wasn't clear.

I don't know if we want to add anything more to the top bar. I left this issue here because I was hoping we could brainstorm a better solution. Thoughts @kauffj?

Btw ohwaitingtx, I really do appreciate this. It's awesome that you took the initiative to do this.

**Pull request closed without merging**
