### PR TITLE
Pre-fill metadata on Publish page

### PR DESCRIPTION
**Pull request by alexliebowitz**
Also includes some general refactoring and improvements to the state management

### CODE REVIEW

**Comment by kauffj** [comment]
@alexliebowitz what needs to happen to merge this?

**Comment by kauffj** [comment]
Related? https://github.com/lbryio/lbry-app/issues/186

**Comment by alexliebowitz** [comment]
Just need to finish writing. The biggest part is done (refactoring so the metadata fields are controlled). I got stuck because I've been receiving a blank set in the "myClaims" prop and had trouble debugging it; there's a lot of Redux-y indirection that was giving me a headache. Good way to learn the new codebase, though. Over the weekend I'm going to plow through and finish this. IIRC that issue started happening suddenly for no apparent reason, which makes me think it's a daemon bug. If it is, I'll make a simple mock for the correct behavior and file an issue in the lbry repo.

**Comment by alexliebowitz** [comment]
#186 is related in that the updates won't actually work properly until we fix that. But this is purely form filling logic within the Publish page, doesn't touch Redux at all.

**Comment by alexliebowitz** [comment]
Whew. Figured out the issue with the myClaims prop being empty.

The Publish page is populating the prop with a value from the Redux store: https://github.com/lbryio/lbry-app/blob/master/ui/js/page/publish/index.js#L15

... but it never actually dispatches an action to call `file_list_mine` and get the value, so it defaults to an empty set:
https://github.com/lbryio/lbry-app/blob/master/ui/js/selectors/claims.js#L84

But the My Files page does request the info: https://github.com/lbryio/lbry-app/blob/master/ui/js/page/fileListDownloaded/index.js#L24

So the prop is only populated if you have already visited the My Files page. If you haven't visited My Files, the Publish page will act like you have no claims, and if you enter the name of something you already published, it doesn't indicate that you're updating an old claim. (This is happening on master too.)

Now that I finally figured that out, tomorrow I will fix this bug, finish the pre-fill stuff, and everything should be ready for review by late tomorrow.

@kauffj

**Comment by kauffj** [comment]
You might want to check out #192, seems related.

**Comment by 6ea86b96** [comment]
Can I help out at all on this @alexliebowitz?

**Pull request merged**
