### PR TITLE
Add go to page navigation to channel pagination options

### LINKED ISSUE #711: Add "go to page" navigation to channel pagination options
## The Issue
For channels with many pages of content, the current pagination option allows you to skip forward one or two pages or click the last 2.  There is no option to go directly to a particular page. The current workaround would be to change the page number in the address bar. 

Would be a good feature to add - possibly by clicking the ellipses (need to indicate this somehow) or having a separate "Go to Page" option altogether. 

### Steps to reproduce
1. Go to lbry://@NileRed
2. Can go forward a couple pages or to the end

### Expected behaviour
Allow users to skip to any page they want

### Actual behaviour
Can skip page by page, or use address bar

## System Configuration

 

- LBRY Daemon version:
- LBRY App version:
- LBRY Installation ID:
- Operating system:

### PR DESCRIPTION
**Pull request by miikkatu**
This would close #711.

The component used for pagination (react-navigate) doesn't offer customisation options, so a separate control for choosing the target page is needed. The implementation is such that the user would enter a page number and presses the enter key.

unfocused

focused

### CODE REVIEW

**Comment by seanyesmunt** [comment]
Please feel free to reach out on discord if you have any questions!

**Comment by miikkatu** [comment]
I updated the PR. I agree that the suggested solution is definitely better.

I also fixed some unrelated issues in the same file that prevented committing, because of the new rules introduced after the initial PR.

The new version looks like this:

screen shot 2018-03-30 at 19 34 20

**Comment by seanyesmunt** [comment]
@miikkatu Awesome! Looking a lot better. Could you just change the `paginate-channel` id to a class?

**Comment by miikkatu** [comment]
That id is now a class, done!

**Comment by seanyesmunt** [comment]
Sweet! I'll merge once the tests pass. @tzarebczan Will reach out with LBC payment

**Pull request merged**
