### PR TITLE
Issue #253 mp3 audio seek fix

### PR DESCRIPTION
**Pull request by akinwale**
Implemented a workaround to load the entire media file using xhr if an audio media element is detected after the metadata is loaded.

I published a test MP3 file to lbry://beyed.

### CODE REVIEW

**Comment by 6ea86b96** [comment]
What is that actual cause of this issue? It's only a subset of audio files that are not seekable afaik. Seems a bit unfortunate if we have to download the entire file for all audio files to fix the bad ones.

**Comment by akinwale** [comment]
According to the issue at https://github.com/lbryio/lbry-app/issues/253, it appears that the player cannot seek through the file until it has finished playing at least once, which indicates that the length is not determined when the media file is first loaded. I can try to limit this to just files with the have the content type, "audio/mpeg3" or "audio/mpeg". Although it's not perfect, it limits the full load to just MP3 audio files.

**Comment by kauffj** [comment]
I'd like confirmation that the [render-media](https://github.com/feross/render-media) plugin has this issue for all MP3s before merging this. @akinwale could you try confirming this issue exists with the plugin directly?

**Comment by akinwale** [comment]
@kauffj From further testing, I tried adding the audio element to the media container directly using `downloadPath` for the `src` attribute, and the audio was seekable, so it looks like the problem could be with the render-media plugin, perhaps with the way the file stream is being created. Considering this is the case, I think we can handle the `audio/mpeg` content type differently by appending the HTML5 audio element directly, while every other type content type will be handled by render-media. What do you recommend?

**Comment by akinwale** [comment]
@6ea86b96 I tried to use this but it doesn't work. The seekable time range end returns a value (which is less than the audio duration), but I am still unable to seek when I try to drag the control.

**Comment by kauffj** [comment]
@akinwale Bypassing render-media and using the audio element directly sounds like a reasonable solution to me.

**Comment by akinwale** [comment]
@kauffj Pushed a new commit.
* Added the `contentType` property to the `VideoPlayer` component.
* Added a `renderAudio` method which is used instead of render-media if the `contentType` is `audio/mpeg3` or `audio/mpeg`.
* Merged with master to resolve conflicts.

**Pull request merged**
