### PR TITLE
Fix CreditAmount

### LINKED ISSUE #344: Content shown as free, charged LBC
## The Issue
We've had a couple reports of users seeing the It's a Disaster video as Free, when in reality it costs 7-9 LBC (depending on LBC price).  When a user tries to download, they are still charged the LBC.  I've seen this happen on my own machine too, but not sure what exactly caused it.  When discussed within the team, it's most likely a caching issue. One time I did get an exchange error, so that may be related also.  When going to settings > Refresh the Cache, the price then shows correctly.

@6ea86b96 is aware of problem but we wanted to log it officially. 

### Steps to reproduce
1. Load LBRY
2. It's a Disaster shown as free
3. Download it, but get charged LBC

### Expected behaviour
Should not show as free, but even if it did, it should double check the price before downloading

### Actual behaviour
Content shown as free, but charged LBC when downloaded.

## System Configuration

 

- LBRY Daemon version: 0.13.1
- LBRY App version: 0.13
- LBRY Installation ID:
- Operating system: Windows

## Anything Else

```shell
2017-07-05 16:15:48,789 WARNING  lbrynet.lbrynet_daemon.ExchangeRateManager:69: There was a problem updating BTCLBC exchange rate information from lbry.io
2017-07-05 16:15:48,795 WARNING  lbrynet.lbrynet_daemon.ExchangeRateManager:69: There was a problem updating USDBTC exchange rate information from Coinbase via Google finance
```

## Screenshots

disaster free

### PR DESCRIPTION
**Pull request by btzr-io**
### Fixes
Fix for #461
Possible fix #344 ( can't confirm, probably not )

### Todo
- [ ] Allow user to see / toggle full price ( #466  )

### CODE REVIEW

**Comment by btzr-io** [comment]
> I know this: 0.0018893955352 looks ugly but I think the app should be transparent about prices

**Comment by btzr-io** [comment]
fix-price

**Comment by btzr-io** [comment]
https://github.com/lbryio/lbry-app/issues/461#issuecomment-321442168

**Comment by btzr-io** [comment]
Any feedback / review would be helpful... ^^

**Comment by kauffj** [comment]
Merged, but made some additional changes so not auto-closed by GitHub.

**Pull request closed without merging**
