### PR TITLE
Added max_key_fee setting(WIP)

### LINKED ISSUE #268: Allow configuring of max_key_fee daemon config
Related lbry issue: https://github.com/lbryio/lbry/issues/721

### PR DESCRIPTION
**Pull request by hackrush01**
Enables users to set the max_key_fee value from UI.(buggy)
Fixes #268

### CODE REVIEW

**Comment by 6ea86b96** [comment]
@hackrush01 there's already a PR for this :) https://github.com/lbryio/lbry-app/pull/278

**Comment by kauffj** [comment]
we discussed this on slack

**Comment by kauffj** [comment]
This is still not working for me, I receive a daemon error. Also, I am unable to change the input value.

**Comment by hackrush01** [comment]
New PR opened

**Pull request closed without merging**
