### PR TITLE
Do not kill an existing daemon, but check if one exists

### LINKED ISSUE #298: LBRY installer must detect running daemon
## The Issue
Under certain conditions (have not reproduced successfully), the daemon is not updated on an existing Windows installation.  I was on 0.12.2RC2 with 0.13RC1 daemon.  I then ran the RC7 exe file. After running LBRY, the daemon stayed at 0.13RC1 - I confirmed that the daemon wasn't updated in the Program Files directory.  In this particular instance, 

Do we check if the daemon is running during install, or only lbry.exe? 

### Steps to reproduce
1. Install 0.12.2RC2, run lbry
2. Download 0.12.2RC7, install update. Lbry may or may not have been closed at this point. 
3. Lbry updates, but daemon still at old version. Not sure if daemon was running during update. 

### Expected behaviour
Daemon should be updated

### Actual behaviour
Daemon exe file was left untouched

## System Configuration

 

- LBRY Daemon version: 0.13.1RC1
- LBRY App version: 0.12.2RC2/0.12.2.RC7
- LBRY Installation ID:
- Operating system: Windows 7

### PR DESCRIPTION
**Pull request by IGassmann**
This removes the functionality of killing an existing daemon and instead checks for an existing one and connect to it.

This will also close #298.

### CODE REVIEW

**Comment by IGassmann** [comment]
This will wait for https://github.com/electron-userland/electron-builder/commit/ad199c45525814aba4c457254a2a259c44383486 to be released.

**Comment by kauffj** [comment]
@IGassmann are you sure daemon killing actually happens? Is it default behavior? I'm relatively confident that if I launch `lbrynet-daemon` from the command line and then the app, that it will connect to that running instance already.

**Comment by IGassmann** [comment]
@kauffj that was the behavior before the refactoring. However, during the refactoring I made the app to kill any existing daemon before starting in order to fix #298. With the coming electron-builder release it won't be necessary anymore.

**Comment by kauffj** [comment]
:+1:

**Comment by tzarebczan** [comment]
@IGassmann does electron builder need to be updated again after the lastest commit in: https://github.com/electron-userland/electron-builder/issues/2516

**Comment by IGassmann** [comment]
@tzarebczan Yes, I'm waiting for 20.5.0 to be released for upgrading. It'll also solve this: https://github.com/electron-userland/electron-builder/issues/2670.

Thanks for notifying me.

**Pull request merged**
