### PR TITLE
Fix files don't display correctly in-app anymore

### PR DESCRIPTION
**Pull request by btzr-io**
### Changes
 Fix text/HTML files don't display correctly in-app anymore #1379
### Todo 
- [x] Display media element after loading metadata

### CODE REVIEW

**Comment by seanyesmunt** [comment]
@btzr-io I see you still have an item under `TODO`, do you plan to do this?

**Comment by btzr-io** [comment]
@seanyesmunt What's the appropriate way to handle this?

loader

**Comment by btzr-io** [comment]
@seanyesmunt  ok it's done.

**Comment by kauffj** [comment]
FYI @daovist I think you're touching some of the same code as this PR.

(This PR is still good/useful, just flagging so he doesn't duplicate effort.)

**Pull request merged**
