### PR TITLE
Fix markdown

### PR DESCRIPTION
**Pull request by btzr-io**
### Changes
Fix markdown render #1179 

### Test
Test for all supported features.
> lbry://content-type#c2740b0ccd93fc7aae7e094dc078dcb178bd9a6c

### Security test
- [Markdown's XSS Vulnerability (and how to mitigate it)](https://github.com/showdownjs/showdown/wiki/Markdown%27s-XSS-Vulnerability-(and-how-to-mitigate-it))

- [Markdown XSS Payloads](https://github.com/cujanovic/Markdown-XSS-Payloads)

> lbry://markdown-xss#deb9947d603c63dc3a7350bd83212836b74a16cc

### Todo
- [x] Security test
- [x] Filter url
- [x] Confirmation for external links https://github.com/lbryio/lbry-app/issues/1442

### CODE REVIEW

**Comment by tzarebczan** [comment]
@btzr-io - do you think we can handle lbry:// links internally, or should we have them call open.lbry.io somehow?
 
[*THE UNMASKING, Part 2: The \"Scam Artist\"*](lbry://theunmasking-part2-thescamartist)"

Example at the bottom of lbry://@NorVegan#5cd109fb589944d1045a670dc4126e2640b0dccb/theunmasking-part1-thenarcissist

**Comment by tzarebczan** [comment]
Also, should/could we show hyperlinks on hover over? Traditional browsers have a status bar which would show the target link. 

Otherwise this PR looks great to me...much better than what we had before (barely any support).

**Comment by seanyesmunt** [comment]
They should definitely be handled internally

**Comment by seanyesmunt** [comment]
Finally tested this. This is awesome!! I merged the `lbry-redux` change, I think you just need to change `url` to `uri` for the modal to work properly. One thing, all the headers look the same to me (not a big deal). This is really cool

screen shot 2018-05-10 at 7 16 50 pm

**Comment by seanyesmunt** [comment]
@jiggytom that link doesn't work for me

**Comment by btzr-io** [comment]
### Todo
- [ ] Fix Invalid claim uri (local links) breaks app.

**Comment by btzr-io** [comment]
@seanyesmunt I added a basic test for local links.
BTW Is there a way to validate a lbry uri?
currently the app breaks if you click a uri like: `lbry:wrong#url`

**Comment by btzr-io** [comment]
> Navigate to invalid uri breaks app (green screen + errors)

@tzarebczan is this a known / valid issue ? ^^

**Comment by btzr-io** [comment]
I totally forgot about `lbryURI`, I'll implement this ASAP :stuck_out_tongue: 
https://github.com/lbryio/lbry-redux/blob/master/src/lbryURI.js

**Comment by btzr-io** [comment]
> One thing, all the headers look the same 

@seanyesmunt I think @kauffj wanted to just keep one type of heading: `h3`
> I'd say allow h3 and smaller and tables. https://github.com/lbryio/lbry-app/issues/1179#issuecomment-382875571

I think is better to just set all titles to the same size to have more consistency.

**Comment by kauffj** [comment]
@btzr-io I think some variation in heading sizing is useful for information layout. But I agree using CSS to restrict sizing rather than restricting the tags themself is a superior solution. So maybe just size h1, h2, h3 all the same?

**Comment by btzr-io** [comment]
I think `h1` and `h2` are commonly used for titlles and h3...h6 for subtitles ( see example)

Github markdown:

# H1
## H2
### H3
### H4
### H5
### H6

**Comment by btzr-io** [comment]
### Todo
- [ ] Fix heading size: https://github.com/lbryio/lbry-app/pull/1441#issuecomment-388399632

**Comment by kauffj** [comment]
@btzr-io what I'm trying to avoid in both of my suggestions is rendered markup with headers that is larger than the content outside of it. Basically, I don't want people to be able to break the sizing hierarchy that their content is embedded inside of. Hopefully that made sense. As long as we're doing that, I'm not particularly attached to any one solution.

**Comment by seanyesmunt** [comment]
This is awesome

**Pull request merged**
