### PR TITLE
Minor redesign

### PR DESCRIPTION
**Pull request by btzr-io**
A bunch of minor `CSS` fixes and additional changes.
### Changes
- [x] Update themes.
- [x] Tabs (redesign) #576
- [x] Custom styled scrollbar #574 
- [x] Update changelog.
### Fixes
- [x] Fix: unresponsive header #613 
- [x] Fix: Dark theme issues
- [x] Minor Fix: https://github.com/lbryio/lbry-app/issues/620
- [x] Minor css fixes.

### Todo
~Update changelog.~

### Removed

This fixes were removed because they require a lot of changes and thinking 
due to the current poor`UI / UX` :stuck_out_tongue: 

This would be handle in their own PR or the main one -> #598 
> ~Init implementation of empty states #551~
> ~Fix: Page titles in search bar don't stand out enough #252~
> ~Thumbnail Resizing In Search/Browsing #595~

Actually this isn't a css bug, see #620, #551
> ~UI glitch after accessing a video without enough credits #605~

### CODE REVIEW

**Comment by MSFTserver** [comment]
should add in something where if the field for licence is blank to not display it or display none instead of a blank licence area

**Comment by btzr-io** [comment]
fix conflicts https://github.com/lbryio/lbry-app/pull/612/commits/2e285822774a995d6cbbc2b9f3713b72947f6c4d

**Comment by btzr-io** [comment]
@kauffj if you aren't ok merging this in master I can move it to redesign, but this was intended to be a `css-patch` for the next release. :stuck_out_tongue:

**Comment by kauffj** [comment]
I expect to put this into 0.17 release

**Comment by btzr-io** [comment]
Ok then I guess we have more time to add more stuff ^^

**Pull request merged**
