### PR TITLE
Autoplay

### PR DESCRIPTION
**Pull request by daovist**
Add autoplay client setting

Video component calls doPlayUri at componentWillMount if selectAutoplay is true

### CODE REVIEW

**Comment by seanyesmunt** [comment]
It should set it on `componentDidMount` to be safe.

**Comment by daovist** [comment]
What I have here works but I am getting an error in the console:

`Uncaught (in promise) DOMException: The play() request was interrupted by a new load request.`

Should I try to [fix this with a promise](https://developers.google.com/web/updates/2017/06/play-request-was-interrupted) or something?

**Comment by seanyesmunt** [comment]
@daovist Seems like that link offers a safe way to fix the error you are seeing.

**Comment by daovist** [comment]
@seanyesmunt I am trying to resolve the error but since it fails silently outside the console I have had another issue that I have been more focused on here.

I am unable to purchase videos, so I can't figure out what I need to make this work for purchased videos. I have tried many times, and even reinstalled LBRY, but I have been unable to download a single non-free video. Several times I have been charged though.

**Comment by tzarebczan** [comment]
@liamcardenas , what's the next step here? I can give this a test later on today also.

**Comment by tzarebczan** [comment]
@daovist, I'll reach out to you on Discord regarding purchasing issues.

**Pull request closed without merging**
