### PR TITLE
Convert all remaining old-style components to ES6 classes (WIP)

### PR DESCRIPTION
**Pull request by alexliebowitz**
Close to done. There are probably still a few callbacks that need to be wrapped in arrow functions.

### CODE REVIEW

**Comment by 6ea86b96** [comment]
@alexliebowitz there's a huge refactoring already in https://github.com/lbryio/lbry-app/tree/redux where, among other things, everything has been switched to ES6 classes.

**Comment by alexliebowitz** [comment]
I'm in the loop about the Redux branch and I've been coordinating with Jeremy to make sure we don't duplicate effort. This PR is actually based on the Redux branch, which does have a lot of components that hadn't been converted yet (e.g. [Publish page](https://github.com/lbryio/lbry-app/blob/redux/ui/js/page/publish/view.jsx).

**Comment by 6ea86b96** [comment]
ah, ok, all good then :)

**Comment by kauffj** [comment]
Even though this is marked WIP, I'm going to merge this now since it'll only diverge further.

**Pull request merged**
