### PR TITLE
Nullify the window when its closed

### PR DESCRIPTION
**Pull request by Jeremy1026**

### CODE REVIEW

**Comment by tzarebczan** [comment]
@Jeremy1026 can you be a little more descriptive in terms of what this fixes? I linked the issue to the PR (with the Zenhub plugin), but would be good to address that in your comments

**Comment by Jeremy1026** [comment]
Sure. The window object currently remains instantiated even after closing it. In macOS clicking the dock icon brings forward all windows of that application. Since the window has been closed, but not removed from memory, macOS still thinks it exists. This fix removes references to the window when it is closed, so that when the dock icon is clicked it will recreate the application window.

This should carry over to Windows/Linux users as well, but needs to be tested on those OS builds to confirm. I don’t currently have those VMs set up to fully test them though.

**Comment by tzarebczan** [comment]
@Jeremy1026 don't have issues bringing LBRY back up after closing to tray on Windows/Ubuntu.

**Comment by tzarebczan** [comment]
This might be fixed by https://github.com/lbryio/lbry-app/pull/1042 also, @Jeremy1026 can you confirm?

**Comment by seanyesmunt** [comment]
Yeah just tested #1042 and confirmed it fixes #1021

**Comment by Jeremy1026** [comment]
Looks good to me as well.

**Pull request closed without merging**
