### PR TITLE
Show exact wallet balance on mouse hover over

### PR DESCRIPTION
**Pull request by miikkatu**
This implements #1259.

### CODE REVIEW

**Comment by miikkatu** [comment]
Balance color issue is now fixed!

**Comment by seanyesmunt** [comment]
Sweet! Just add a changelog to this too and I will merge

**Comment by miikkatu** [comment]
Changelog updated.

**Comment by tzarebczan** [comment]
Thanks @miikkatu! Have your contribution email, will follow up soon!

**Pull request merged**
