### PR TITLE
Add a message about token security [issue #523]

### PR DESCRIPTION
**Pull request by MSFTserver**
image

### CODE REVIEW

**Comment by MSFTserver** [comment]
image

**Comment by MSFTserver** [comment]
lol i still cant figure out how to request reviews @btzr-io

**Comment by MSFTserver** [comment]
could even give it its own class and add red highlight or something to make it stand out more

**Comment by kauffj** [comment]
Fixed in https://github.com/lbryio/lbry-app/commit/19165895533dc3c6b5a092b2c22d14730d11bb14

**Comment by kauffj** [comment]
Also, FYI, error messages and styles should never be used stylistically unless an error actually occurred. A notice or warning style would instead be a candidate here.

**Pull request closed without merging**
