### PR TITLE
Improve editing UX

### PR DESCRIPTION
**Pull request by btzr-io**
### Added
Add an edit button inside `fileActions` menu ->   https://github.com/lbryio/lbry-app/issues/415

### Fixes
 Fix for https://github.com/lbryio/lbry-app/issues/467

### Todo
- [ ] Test it
- [ ] Display `update` button instead of `publish`
- [ ] Disable update when there is no changes
- [x] Investigate / fix anomaly :alien: #467 
- [x] Revert last commit  fa531e9
- [x] Prevent regression https://github.com/lbryio/lbry-app/issues/186
- [x] Update changelog.md
- [ ] Investigate  https://github.com/lbryio/lbry-app/pull/500#issuecomment-325421083 `?`

### Bugs
~This needs to be fixed first: https://github.com/lbryio/lbry-app/issues/460, https://github.com/lbryio/lbry-app/issues/467~
Bugs where fixed, everything looking good for now :upside_down_face:

### CODE REVIEW

**Comment by kauffj** [comment]
@hackrush01 looks like @btzr-io beat you to this one ;)

**Comment by kauffj** [comment]
@btzr-io I ran this and clicking edit on an item did not pre-fill any of the fields.

**Comment by btzr-io** [comment]
@kauffj  Are you sure, did you get any errors, for me it's working fine :upside_down_face:

**Comment by btzr-io** [comment]
@kauffj @tzarebczan  Need a review / feedback, and a tester :v:

**Comment by btzr-io** [comment]
fix-467

**Comment by lyoshenka** [comment]
@btzr-io if you need a review, please assign reviewers in the right sidebar. thats what we look at to know that something's waiting for review. it helps keep work from falling through the cracks. thanks.

**Comment by btzr-io** [comment]
@lyoshenka  Thanks, yes I would do that but:
> Pull request authors can't request reviews unless they are either a repository owner or collaborator with write access to the repository.

Sorry for the trouble :upside_down_face:

**Comment by tzarebczan** [comment]
@btzr-io I can do the review requests for you, just ping me on slack whenever you are ready for them. I'll assign as appropriate.

**Comment by btzr-io** [comment]
Fix conflicts 62fa991 ^

**Comment by btzr-io** [comment]
Just waiting for the new release...

**Comment by kauffj** [comment]
This still does not work for me. It doesn't retrieve any of the fields. I have tried a few different publishes. 

I have not looked into this in any detail.

You may wish to use the `file_edit` branch, as it is up to date with master and fixes a few merge issues.

**Comment by btzr-io** [comment]
@kauffj I just tested `file_branch` and it's working fine :confused:

**Comment by btzr-io** [comment]
Fixed -> https://github.com/lbryio/lbry-app/pull/526

**Pull request closed without merging**
