### PR TITLE
Add 3D file-viewer support

### PR DESCRIPTION
**Pull request by btzr-io**
### Changes
A basic ThreeJS 3D viewer  based on [Autodesk/3DViewerComponent
](https://github.com/Autodesk/3DViewerComponent)

- Add 3D file-viewing to LBRY desktop app https://github.com/lbryio/lbry-app/issues/1409

### Todo (WIP)
- [x] Threejs + React.
- [x] Load blob from claim
- [x] Show Grid
- [x] Render 3D-model.
- [x] Add 3D-file support for getMediaType function https://github.com/lbryio/lbry-redux/pull/41
- [X] Investigate render bug. https://github.com/mrdoob/three.js/issues/12499#issuecomment-339780204
- [x] Ensure that STL files have valid normal data.
- [x]  Show loading  message
- [x] Handle Errors
- [x] Adaptive Theme (Dark / Light) :art: 
- [x] STL loader support.
- [ ] OBJ loader support.
- [ ] Add basic controls (UI)
- [x] Investigate loading bug :beetle: https://github.com/lbryio/lbry-app/pull/1542#issuecomment-

### CODE REVIEW

**Comment by kauffj** [comment]
@seanyesmunt this is a great and appreciated contrib from @btzr-io, but let's give some thought to the design pattern for a large/flexible number of renderers/viewers based on the file type.

**Comment by btzr-io** [comment]
Maybe use a component that works like a router? 

```JSX
<FileViewer source={file}/>
 // supported 3d-files  ({file}) => <ThreeViewer source={file}/>
 // supported comic files  ({file}) => <ComicReader source={file}/>
 // supported e-book files ({file}) => <EbookReader source={file}/>
 
```

**Comment by kauffj** [comment]
@btzr-io a router pattern looks like it would make a lot of sense here. Want to tackle this? :D

Filed it here: https://github.com/lbryio/lbry-app/issues/1544

(I don't think this PR necessary needs to be blocked over this)

**Comment by seanyesmunt** [comment]
@btzr-io This is looking awesome. Just merged your lbry-redux PR. You can point your package.json at `3bc978ef4e4dcf5af6b1185b530244209100f69f` to get those changes. It looks like this is only rendering the webgl scene, with no actual 3d model, is that right? Still looking great though

**Comment by seanyesmunt** [comment]
oh it loaded this time, not sure what changed

**Comment by seanyesmunt** [comment]
This is so cool though, very seamless.

**Comment by btzr-io** [comment]
Thanks, you need to wait a few seconds, I'm working on a loading screen to prevent confusion.

**Comment by btzr-io** [comment]
New PR (Component code only) https://github.com/lbryio/lbry-app/pull/1558

**Pull request closed without merging**
