### PR TITLE
Update _card.scss

### PR DESCRIPTION
**Pull request by 98farhan94**
Added transition to cards for smoother experience.

### CODE REVIEW

**Comment by kauffj** [comment]
Good idea to add more transitions! However, I would like to avoid transition all. What effects actually need transitions? 

Additionally, there is a `$transition-standard` defined in `_global.scss`, I'd like to continue using this. I'd be fine with changing it from `0.225s ease`, as I don't think that was an especially considered choice.

**Comment by Smurphonomics** [comment]
This works well

`section.card.card--small.card--link:hover {
    z-index: 2;
    -webkit-transition: all 120ms ease-in;
    -webkit-transform: scale(1.1);
    -ms-transition: all 120ms ease-in;
    -ms-transform: scale(1.1);
    -moz-transition: all 120ms ease-in;
    -moz-transform: scale(1.1);
    transition: all 120ms ease-in;
    transform: scale(1.1);
}`

**Comment by kauffj** [comment]
@Smurphonomics we are always in a current version of chrome in this app, so no need for additional browser rules. And I would like to avoid `transition: all`.

**Comment by 98farhan94** [comment]
I think we can just do:

` transition: transform .1s ease-in-out;`c

The scale transform feels very abrupt right now, that's all I wanted to make smoother.

**Comment by kauffj** [comment]
https://github.com/lbryio/lbry-app/commit/7c380ce01b7e9d45399f993a4ade39f9a4adce9d

**Comment by Smurphonomics** [comment]
I saw cross browser SCSS in the app code, so I assumed it was being coded for a web based version also?

A good idea to remove "ALL", as it can have performance issues with it containing hidden code you don't need, catering for ALL properties.

@98farhan94 transition: transform .1s ease-in-out; is much cleaner :)

**Comment by Smurphonomics** [comment]
@98farhan94 For even cleaner and more optimised code, we can omit the "transform" part as everything has already been declared. 

`` 
.card-row > .card {transition: .1s ease-in-out;}

**Comment by 98farhan94** [comment]
@Smurphonomics Okay, I'll append it in a new merge.

**Comment by Smurphonomics** [comment]
Nope. Forget it. I thought omitting ALL would mean it just used the animation on the scale hover event. But it looks like omitting ALL just sets it to the initial state, which is ALL :(

So keep it to `transition: transform .1s ease-in-out;` after all :)

**Comment by kauffj** [comment]
Yep, that's basically what we added @Smurphonomics.

Re: cross-browser, it's from the pre-Electron days and should probably be removed.

**Pull request closed without merging**
