### PR TITLE
Discover Page - Replace horizontal scrollbar with arrows (WIP)

### PR DESCRIPTION
**Pull request by seanyesmunt**
https://github.com/lbryio/lbry-app/issues/250

### CODE REVIEW

**Comment by kauffj** [comment]
@seanyesmunt since this only contains a refactor so far, I'm inclined to close. Would love to see what you come up with here though! 

And would also be open to non-master commit rights if it makes workflow easier.

**Comment by seanyesmunt** [comment]
@kauffj I just got back from a trip, so haven't had much time to work on it so far, but I plan to work on this today/following days. That refactor commit was just an initial commit to get the PR made. I would appreciate if you could reopen the PR (if possible). If not I can just open a new PR.

**Comment by seanyesmunt** [comment]
@kauffj What do you think about using an open source carousel component for this? https://github.com/akiran/react-slick is one I've found that looks especially good (a ton of options).

**Comment by kauffj** [comment]
@seanyesmunt I'm very much in favor of looking at existing solutions, but I'm conservative about adding additional code and dependencies.

My preferred approach here would be to look at the various styles, pick one, and then look at how much of the code we actually need to implement just that specific solution.

Sometimes it ends up that you only need a small minority of the JS/CSS used by the entire component, and you're better off bringing just this specific part in (it also means it will match your naming conventions, styles, etc.).

**Comment by kauffj** [comment]
OTOH if using an off the shelf carousel delivers something more usable than the current version, I'd probably just take it :)

**Comment by seanyesmunt** [comment]
@kauffj sorry to close after I asked you to reopen. I don't really have the time to finish this right now, at least not something I would be happy with. I will continue to look at open issues, and if this is still an outstanding feature request when I am able to continue working I would love to take it back up.

**Pull request closed without merging**
